name: NodeJS with Webpack ,Publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: |
        npm install
        
    - name: build_web
      run: |
        npm run build_web
        
    - name: build_node
      run: |
        npm run build_node
        
    - name: build_types
      run: |
        npm run types
        
    - name: Publish
      run: |
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      
